Add input of country and city through the URL
will-lynas/flask-weather-app pull request #4
Opened 2023-10-16 13:41 UTC by artem-str-31

2023-10-16 14:02 UTC, will-lynas requested changes

2023-10-16 14:02 UTC, will-lynas commented on app.py
> +    result = api_fetch(country_name, city_name)
Now that we are using user supplied data in the api call, we need to handle errors from the api. Make `api_fetch` throw an exception if the api doesn't support a city. Catch the exception in `city_weather` and display a suitable response.

2023-10-16 14:02 UTC, will-lynas commented on app.py
> +            "q": f"{city_name}, {country_name}",
Is the space needed? Does it care if there is a space or not?

2023-10-16 14:48 UTC, will-lynas requested changes

2023-10-16 14:48 UTC, will-lynas commented on app.py
> +    last_result = db.session.query(WeatherData).filter(WeatherData.country.like(country_name), WeatherData.city.like(city_name)).order_by(WeatherData.time.desc()).first()
I don't think we need `like` here since we want an exact match. `==` instead.

2023-10-16 14:48 UTC, will-lynas commented on app.py
> +    last_result = db.session.query(WeatherData).filter(WeatherData.country.like(country_name), WeatherData.city.like(city_name)).order_by(WeatherData.time.desc()).first()
I think it would be better to have the caching stuff in `api_fetch` or in a separate function so that it can be reused.

2023-10-16 14:48 UTC, will-lynas commented on app.py
> +    last_result = db.session.query(WeatherData).filter(WeatherData.country.like(country_name), WeatherData.city.like(city_name)).order_by(WeatherData.time.desc()).first()
Line too long. Add newlines somewhere. We will enforce this with `pylint` in future.

2023-10-16 14:48 UTC, will-lynas commented on app.py
> +    weather_data = WeatherData(country=country_name, city=city_name, temp=response["main"]["temp"], time=time.time())
Newlines

2023-10-16 14:48 UTC, will-lynas commented on app.py
> -def index():
Make index redirect to `/UK/London`

2023-10-17 14:55 UTC, will-lynas requested changes

2023-10-17 14:55 UTC, will-lynas commented on app.py
>          return f"<{self.__class__.__name__} {self.temp} {self.time}>"
Can you add `city` and `country` to the `__repr__`

2023-10-17 14:55 UTC, will-lynas commented on app.py
> +    last_result = db.session.query(WeatherData).filter(WeatherData.country.is_(country_name), WeatherData.city.is_(city_name)).order_by(WeatherData.time.desc()).first()
afaik `is_` is the equivalent of sql `IS` which is for checking for null. I think you literally want `==`.

2023-10-17 14:55 UTC, will-lynas commented on app.py
> +    last_fetch_delta = 0
This line doesn't do anything.

2023-10-17 15:26 UTC, will-lynas approved these changes
Merge (as long as it works locally)

2023-10-17 15:27 UTC, will-lynas commented
And make sure to squash first. `rebase -i origin/main` then `push -f`.

2023-10-17 15:30 UTC, artem-str-31 commented
> And make sure to squash first. `rebase -i origin/main` then `push -f`.
> Or use github.

Should I squash and merge or rebase and merge?

2023-10-17 15:32 UTC, will-lynas commented
`rebase` doesn't actually do anything here. Generally you want to do both, so better to use cmdline. Here you can just you squash and merge.

2023-10-17 15:35 UTC, merged